# Generated by Django 3.0.6 on 2020-05-19 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20200509_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='offerType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.OfferType'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='FirstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='LastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
