# Generated by Django 3.0.6 on 2020-06-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('career', '0003_auto_20200519_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='CompanyLogo',
            field=models.FileField(blank=True, null=True, upload_to='CompanyLogo'),
        ),
        migrations.AddField(
            model_name='intern',
            name='Image',
            field=models.FileField(blank=True, default='ProfileImage/avatar.jpg', null=True, upload_to='ProfileImage'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.Company'),
        ),
        migrations.AlterField(
            model_name='offerapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Inheriter',
        ),
    ]
