# Generated by Django 3.0.6 on 2020-06-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_auto_20200603_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCompanies',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='career.Company')),
                ('Source', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('career.company',),
        ),
    ]
